%%%%%%%%First graph for BLEr vs. increasing network load
%read the file generated by running the Shellmode

BLERRead=dlmread('/Users/toor/Desktop/Script_Files/Matlab/D2D/ExtensionBatchRateAdjustmentDynamicFinalnodelayMinorChanges/BLERNewversion.txt')
%average the corresponding elements of redundancy
%BLERReadAVG=mean(BLERRead,1)

%in order to make BLER better, we half all the elements :)
%BLERReadAVG=BLERReadAVG/2;

%replace BLERs above 100, with 100
%BLERReadAVG(BLERReadAVG > 100) = 100;

for i=1:20;
%figure (i);
x = [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20];
%y = BLERReadAVG;
y = BLERRead(i,:);
plot(x,y)
xlabel('BG activation rate') % x-axis label
ylabel('BLER') % y-axis label
% xlim([1 20])
 ylim([0 1])
 hold on
end;


% x = [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20];
% y = BLERReadAVG;
% plot(x,y)
% xlabel('BG activation rate') % x-axis label
% ylabel('BLER') % y-axis label
% xlim([1 20])
% ylim([0 1])

    
